defaultProject: general-ce
defaultLocation: EU
defaultDataset: dataform_extreme_weather
defaultAssertionDataset: dataform_extreme_weather_assertions
dataformCoreVersion: 3.0.0
defaultNotebookRuntimeOptions:
  outputBucket: gs://dataform_extreme_weather
